/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalRecipientReceivableRefund } from './additionalRecipientReceivableRefund';
import { Money } from './money';

/**
* Represents a monetary distribution of part of a [Transaction](#type-transaction)\'s amount for Transactions which included additional recipients. The location of this receivable is that same as the one specified in the [AdditionalRecipient](#type-additionalrecipient).
*/
export class AdditionalRecipientReceivable {
    /**
    * The additional recipient receivable\'s unique ID, issued by Square payments servers.
    */
    'id': string;
    /**
    * The ID of the transaction that the additional recipient receivable was applied to.
    */
    'transactionId': string;
    /**
    * The ID of the location that created the receivable. This is the location ID on the associated transaction.
    */
    'transactionLocationId': string;
    'amountMoney': Money;
    /**
    * The time when the additional recipient receivable was created, in RFC 3339 format.
    */
    'createdAt'?: string;
    /**
    * Any refunds of the receivable that have been applied.
    */
    'refunds'?: Array<AdditionalRecipientReceivableRefund>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string"
        },
        {
            "name": "transactionLocationId",
            "baseName": "transaction_location_id",
            "type": "string"
        },
        {
            "name": "amountMoney",
            "baseName": "amount_money",
            "type": "Money"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "Array<AdditionalRecipientReceivableRefund>"
        }    ];

    static getAttributeTypeMap() {
        return AdditionalRecipientReceivable.attributeTypeMap;
    }
}

