/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represents a physical address.
*/
export class Address {
    /**
    * The first line of the address.  Fields that start with `address_line` provide the address\'s most specific details, like street number, street name, and building name. They do *not* provide less specific details like city, state/province, or country (these details are provided in other fields).
    */
    'addressLine1'?: string;
    /**
    * The second line of the address, if any.
    */
    'addressLine2'?: string;
    /**
    * The third line of the address, if any.
    */
    'addressLine3'?: string;
    /**
    * The city or town of the address.
    */
    'locality'?: string;
    /**
    * A civil region within the address\'s `locality`, if any.
    */
    'sublocality'?: string;
    /**
    * A civil region within the address\'s `sublocality`, if any.
    */
    'sublocality2'?: string;
    /**
    * A civil region within the address\'s `sublocality_2`, if any.
    */
    'sublocality3'?: string;
    /**
    * A civil entity within the address\'s country. In the US, this is the state.
    */
    'administrativeDistrictLevel1'?: string;
    /**
    * A civil entity within the address\'s `administrative_district_level_1`. In the US, this is the county.
    */
    'administrativeDistrictLevel2'?: string;
    /**
    * A civil entity within the address\'s `administrative_district_level_2`, if any.
    */
    'administrativeDistrictLevel3'?: string;
    /**
    * The address\'s postal code.
    */
    'postalCode'?: string;
    /**
    * The address\'s country, in ISO 3166-1-alpha-2 format. See [Country](#type-country) for possible values
    */
    'country'?: string;
    /**
    * Optional first name when it\'s representing recipient.
    */
    'firstName'?: string;
    /**
    * Optional last name when it\'s representing recipient.
    */
    'lastName'?: string;
    /**
    * Optional organization name when it\'s representing recipient.
    */
    'organization'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addressLine1",
            "baseName": "address_line_1",
            "type": "string"
        },
        {
            "name": "addressLine2",
            "baseName": "address_line_2",
            "type": "string"
        },
        {
            "name": "addressLine3",
            "baseName": "address_line_3",
            "type": "string"
        },
        {
            "name": "locality",
            "baseName": "locality",
            "type": "string"
        },
        {
            "name": "sublocality",
            "baseName": "sublocality",
            "type": "string"
        },
        {
            "name": "sublocality2",
            "baseName": "sublocality_2",
            "type": "string"
        },
        {
            "name": "sublocality3",
            "baseName": "sublocality_3",
            "type": "string"
        },
        {
            "name": "administrativeDistrictLevel1",
            "baseName": "administrative_district_level_1",
            "type": "string"
        },
        {
            "name": "administrativeDistrictLevel2",
            "baseName": "administrative_district_level_2",
            "type": "string"
        },
        {
            "name": "administrativeDistrictLevel3",
            "baseName": "administrative_district_level_3",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Address.attributeTypeMap;
    }
}

