/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class BatchRetrieveInventoryCountsRequest {
    /**
    * Filters results by [CatalogObject](#type-catalogobject) ID. Only applied when set. Default: unset.
    */
    'catalogObjectIds'?: Array<string>;
    /**
    * Filters results by [Location](#type-location) ID. Only applied when set. Default: unset.
    */
    'locationIds'?: Array<string>;
    /**
    * Provided as an RFC 3339 timestamp. Returns results whose `calculated_at` value is after the given time. Default: UNIX epoch (`1970-01-01T00:00:00Z`).
    */
    'updatedAfter'?: string;
    /**
    * A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for the original query.  See [Pagination](/basics/api101/pagination) for more information.
    */
    'cursor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "catalogObjectIds",
            "baseName": "catalog_object_ids",
            "type": "Array<string>"
        },
        {
            "name": "locationIds",
            "baseName": "location_ids",
            "type": "Array<string>"
        },
        {
            "name": "updatedAfter",
            "baseName": "updated_after",
            "type": "string"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BatchRetrieveInventoryCountsRequest.attributeTypeMap;
    }
}

