/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Defines the fields that are included in requests to the BatchRetrieveOrders endpoint.
*/
export class BatchRetrieveOrdersRequest {
    /**
    * The IDs of the orders to retrieve. A maximum of 100 orders can be retrieved per request.
    */
    'orderIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderIds",
            "baseName": "order_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return BatchRetrieveOrdersRequest.attributeTypeMap;
    }
}

