/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SquareError } from './squareError';

/**
* 
*/
export class BatchDeleteCatalogObjectsResponse {
    /**
    * The set of [SquareError](#type-squareerror)s encountered.
    */
    'errors'?: Array<SquareError>;
    /**
    * The IDs of all [CatalogObject](#type-catalogobject)s deleted by this request.
    */
    'deletedObjectIds'?: Array<string>;
    /**
    * The database [timestamp](#workingwithdates) of this deletion in RFC 3339 format, e.g., \"2016-09-04T23:59:33.123Z\".
    */
    'deletedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        },
        {
            "name": "deletedObjectIds",
            "baseName": "deleted_object_ids",
            "type": "Array<string>"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BatchDeleteCatalogObjectsResponse.attributeTypeMap;
    }
}

