/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class BatchRetrieveCatalogObjectsRequest {
    /**
    * The IDs of the [CatalogObject](#type-catalogobject)s to be retrieved.
    */
    'objectIds': Array<string>;
    /**
    * If `true`, the response will include additional objects that are related to the requested objects, as follows:  If the `objects` field of the response contains a [CatalogItem](#type-catalogitem),  its associated [CatalogCategory](#type-catalogcategory), [CatalogTax](#type-catalogtax)es, [CatalogImage](#type-catalogimage)s and [CatalogModifierList](#type-catalogmodifierlist)s will be returned in the `related_objects` field of the response. If the `objects` field of the response contains a [CatalogItemVariation](#type-catalogitemvariation), its parent [CatalogItem](#type-catalogitem) will be returned in the `related_objects` field of the response.
    */
    'includeRelatedObjects'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>"
        },
        {
            "name": "includeRelatedObjects",
            "baseName": "include_related_objects",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BatchRetrieveCatalogObjectsRequest.attributeTypeMap;
    }
}

