/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogModifierOverride } from './catalogModifierOverride';

/**
* Controls the properties of a [CatalogModifierList](#type-catalogmodifierlist) as it applies to this [CatalogItem](#type-catalogitem).
*/
export class CatalogItemModifierListInfo {
    /**
    * The ID of the [CatalogModifierList](#type-catalogmodifierlist) controlled by this [CatalogModifierListInfo](#type-catalogmodifierlistinfo).
    */
    'modifierListId': string;
    /**
    * A set of [CatalogModifierOverride](#type-catalogmodifieroverride) objects that override whether a given [CatalogModifier](#type-catalogmodifier) is enabled by default.
    */
    'modifierOverrides'?: Array<CatalogModifierOverride>;
    /**
    * If zero or larger, the smallest number of [CatalogModifier](#type-catalogmodifier)s that must be selected from this [CatalogModifierList](#type-catalogmodifierlist).
    */
    'minSelectedModifiers'?: number;
    /**
    * If zero or larger, the largest number of [CatalogModifier](#type-catalogmodifier)s that can be selected from this [CatalogModifierList](#type-catalogmodifierlist).
    */
    'maxSelectedModifiers'?: number;
    /**
    * If `true`, enable this [CatalogModifierList](#type-catalogmodifierlist).
    */
    'enabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modifierListId",
            "baseName": "modifier_list_id",
            "type": "string"
        },
        {
            "name": "modifierOverrides",
            "baseName": "modifier_overrides",
            "type": "Array<CatalogModifierOverride>"
        },
        {
            "name": "minSelectedModifiers",
            "baseName": "min_selected_modifiers",
            "type": "number"
        },
        {
            "name": "maxSelectedModifiers",
            "baseName": "max_selected_modifiers",
            "type": "number"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CatalogItemModifierListInfo.attributeTypeMap;
    }
}

