/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A tax in the Catalog object model.
*/
export class CatalogTax {
    /**
    * The tax\'s name. Searchable. This field has max length of 255 Unicode code points.
    */
    'name'?: string;
    /**
    * Whether the tax is calculated based on a payment\'s subtotal or total. See [TaxCalculationPhase](#type-taxcalculationphase) for possible values
    */
    'calculationPhase'?: string;
    /**
    * Whether the tax is `ADDITIVE` or `INCLUSIVE`. See [TaxInclusionType](#type-taxinclusiontype) for possible values
    */
    'inclusionType'?: string;
    /**
    * The percentage of the tax in decimal form, using a `\'.\'` as the decimal separator and without a `\'%\'` sign. A value of `7.5` corresponds to 7.5%.
    */
    'percentage'?: string;
    /**
    * If `true`, the fee applies to custom amounts entered into the Square Point of Sale app that are not associated with a particular [CatalogItem](#type-catalogitem).
    */
    'appliesToCustomAmounts'?: boolean;
    /**
    * If `true`, the tax will be shown as enabled in the Square Point of Sale app.
    */
    'enabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "calculationPhase",
            "baseName": "calculation_phase",
            "type": "string"
        },
        {
            "name": "inclusionType",
            "baseName": "inclusion_type",
            "type": "string"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string"
        },
        {
            "name": "appliesToCustomAmounts",
            "baseName": "applies_to_custom_amounts",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CatalogTax.attributeTypeMap;
    }
}

