/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class CatalogQueryText {
    /**
    * A list of one, two, or three search keywords. Keywords with fewer than three characters are ignored.
    */
    'keywords': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CatalogQueryText.attributeTypeMap;
    }
}

