/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Defines how prices are modified or set for items that match the pricing rule during the active time period.
*/
export class CatalogPricingRule {
    /**
    * User-defined name for the pricing rule. For example, \"Buy one get one free\" or \"10% off\".
    */
    'name'?: string;
    /**
    * Unique ID for the [CatalogTimePeriod](#type-catalogtimeperiod)s when this pricing rule is in effect. If left unset, the pricing rule is always in effect.
    */
    'timePeriodIds'?: Array<string>;
    /**
    * Unique ID for the [CatalogDiscount](#type-catalogdiscount) to take off the price of all matched items.  Only one of `total_price_money`, `item_price`, or `discount` can be supplied.
    */
    'discountId'?: string;
    /**
    * Unique ID for the [CatalogProductSet](#type-catalogproductset) that will be matched by this rule. A match rule matches within the entire cart.
    */
    'matchProductsId'?: string;
    /**
    * The [CatalogProductSet](#type-catalogproductset) to apply the pricing rule to within the set of matched products specified by `match_products_id`. An apply rule can only match once within the set of matched products. If left unset, the pricing rule will be applied to all products within the set of matched products.
    */
    'applyProductsId'?: string;
    /**
    * Identifies the [CatalogProductSet](#type-catalogproductset) to exclude from this pricing rule. An exclude rule matches within the subset of the cart that fits the match rules (the match set). An exclude rule can only match once in the match set. If not supplied, the pricing will be applied to all products in the match set. Other products retain their base price, or a price generated by other rules.
    */
    'excludeProductsId'?: string;
    /**
    * Represents the date the Pricing Rule is valid from. Represented in RFC3339 full-date format (YYYY-MM-DD).
    */
    'validFromDate'?: string;
    /**
    * Represents the local time the pricing rule should be valid from. Time zone is determined by the device running the Point of Sale app.  Represented in RFC3339 partial-time format (HH:MM:SS). Partial seconds will be truncated.
    */
    'validFromLocalTime'?: string;
    /**
    * Represents the date the pricing rule will become inactive.  Represented in RFC3339 full-date format (YYYY-MM-DD).
    */
    'validUntilDate'?: string;
    /**
    * Represents the local time at which the pricing rule will become inactive. Time zone is determined by the device running the Point of Sale app.  Represented in RFC3339 partial-time format (HH:MM:SS). Partial seconds will be truncated.
    */
    'validUntilLocalTime'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "timePeriodIds",
            "baseName": "time_period_ids",
            "type": "Array<string>"
        },
        {
            "name": "discountId",
            "baseName": "discount_id",
            "type": "string"
        },
        {
            "name": "matchProductsId",
            "baseName": "match_products_id",
            "type": "string"
        },
        {
            "name": "applyProductsId",
            "baseName": "apply_products_id",
            "type": "string"
        },
        {
            "name": "excludeProductsId",
            "baseName": "exclude_products_id",
            "type": "string"
        },
        {
            "name": "validFromDate",
            "baseName": "valid_from_date",
            "type": "string"
        },
        {
            "name": "validFromLocalTime",
            "baseName": "valid_from_local_time",
            "type": "string"
        },
        {
            "name": "validUntilDate",
            "baseName": "valid_until_date",
            "type": "string"
        },
        {
            "name": "validUntilLocalTime",
            "baseName": "valid_until_local_time",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CatalogPricingRule.attributeTypeMap;
    }
}

