/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An image file to use in Square catalogs. Can be associated with catalog items, item variations, and categories.
*/
export class CatalogImage {
    /**
    * The internal name of this image. Identifies this image in calls to the Connect APIs.
    */
    'name'?: string;
    /**
    * The URL of this image. Generated by Square after an image is uploaded to the CreateCatalogImage endpoint.
    */
    'url'?: string;
    /**
    * A caption that describes what is shown in the image. Displayed in the Square Online Store.
    */
    'caption'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CatalogImage.attributeTypeMap;
    }
}

