/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogObject } from './catalogObject';

/**
* A batch of [CatalogObject](#type-catalogobject)s.
*/
export class CatalogObjectBatch {
    /**
    * A list of [CatalogObject](#type-catalogobject)s belonging to this batch.
    */
    'objects'?: Array<CatalogObject>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<CatalogObject>"
        }    ];

    static getAttributeTypeMap() {
        return CatalogObjectBatch.attributeTypeMap;
    }
}

