/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An Items Connect V1 object ID along with its associated [location](#type-location) ID.
*/
export class CatalogV1Id {
    /**
    * The ID for an object in Connect V1, if different from its Connect V2 ID.
    */
    'catalogV1Id'?: string;
    /**
    * The ID of the [location](#type-location) this Connect V1 ID is associated with.
    */
    'locationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "catalogV1Id",
            "baseName": "catalog_v1_id",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CatalogV1Id.attributeTypeMap;
    }
}

