/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates whether a [CatalogModifierList](#type-catalogmodifierlist) supports multiple selections.
*/
export enum CatalogModifierListSelectionType {
    SINGLE = <any> 'SINGLE',
    MULTIPLE = <any> 'MULTIPLE'
}
