/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateOrderRequestDiscount } from './createOrderRequestDiscount';
import { CreateOrderRequestLineItem } from './createOrderRequestLineItem';
import { CreateOrderRequestTax } from './createOrderRequestTax';
import { Order } from './order';

/**
* 
*/
export class CreateOrderRequest {
    'order'?: Order;
    /**
    * A value you specify that uniquely identifies this order among orders you\'ve created.  If you\'re unsure whether a particular order was created successfully, you can reattempt it with the same idempotency key without worrying about creating duplicate orders.  See [Idempotency](/basics/api101/idempotency) for more information.
    */
    'idempotencyKey'?: string;
    /**
    * __Deprecated__: Please set the reference_id on the nested [order](#type-order) field instead.  An optional ID you can associate with the order for your own purposes (such as to associate the order with an entity ID in your own database).  This value cannot exceed 40 characters.
    */
    'referenceId'?: string;
    /**
    * __Deprecated__: Please set the line_items on the nested [order](#type-order) field instead.  The line items to associate with this order.  Each line item represents a different product to include in a purchase.
    */
    'lineItems'?: Array<CreateOrderRequestLineItem>;
    /**
    * __Deprecated__: Please set the taxes on the nested [order](#type-order) field instead.  The taxes to include on the order.
    */
    'taxes'?: Array<CreateOrderRequestTax>;
    /**
    * __Deprecated__: Please set the discounts on the nested [order](#type-order) field instead.  The discounts to include on the order.
    */
    'discounts'?: Array<CreateOrderRequestDiscount>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "order",
            "baseName": "order",
            "type": "Order"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string"
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "Array<CreateOrderRequestLineItem>"
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "Array<CreateOrderRequestTax>"
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Array<CreateOrderRequestDiscount>"
        }    ];

    static getAttributeTypeMap() {
        return CreateOrderRequest.attributeTypeMap;
    }
}

