/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BreakType } from './breakType';
import { SquareError } from './squareError';

/**
* The response to the request to create a `BreakType`. Contains the created `BreakType` object. May contain a set of `SquareError` objects if the request resulted in errors.
*/
export class CreateBreakTypeResponse {
    'breakType'?: BreakType;
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<SquareError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "breakType",
            "baseName": "break_type",
            "type": "BreakType"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        }    ];

    static getAttributeTypeMap() {
        return CreateBreakTypeResponse.attributeTypeMap;
    }
}

