/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BreakType } from './breakType';

/**
* A request to create a new `BreakType`
*/
export class CreateBreakTypeRequest {
    /**
    * Unique string value to insure idempotency of the operation
    */
    'idempotencyKey'?: string;
    'breakType': BreakType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string"
        },
        {
            "name": "breakType",
            "baseName": "break_type",
            "type": "BreakType"
        }    ];

    static getAttributeTypeMap() {
        return CreateBreakTypeRequest.attributeTypeMap;
    }
}

