/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Defines the body parameters that can be provided in a request to the CreateMobileAuthorizationCode endpoint.
*/
export class CreateMobileAuthorizationCodeRequest {
    /**
    * The Square location ID the authorization code should be tied to.
    */
    'locationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateMobileAuthorizationCodeRequest.attributeTypeMap;
    }
}

