/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates the method used to create the customer profile.
*/
export enum CustomerCreationSource {
    OTHER = <any> 'OTHER',
    APPOINTMENTS = <any> 'APPOINTMENTS',
    COUPON = <any> 'COUPON',
    DELETION_RECOVERY = <any> 'DELETION_RECOVERY',
    DIRECTORY = <any> 'DIRECTORY',
    EGIFTING = <any> 'EGIFTING',
    EMAIL_COLLECTION = <any> 'EMAIL_COLLECTION',
    FEEDBACK = <any> 'FEEDBACK',
    IMPORT = <any> 'IMPORT',
    INVOICES = <any> 'INVOICES',
    LOYALTY = <any> 'LOYALTY',
    MARKETING = <any> 'MARKETING',
    MERGE = <any> 'MERGE',
    ONLINE_STORE = <any> 'ONLINE_STORE',
    INSTANT_PROFILE = <any> 'INSTANT_PROFILE',
    TERMINAL = <any> 'TERMINAL',
    THIRD_PARTY = <any> 'THIRD_PARTY',
    THIRD_PARTY_IMPORT = <any> 'THIRD_PARTY_IMPORT',
    UNMERGE_RECOVERY = <any> 'UNMERGE_RECOVERY'
}
