/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './address';
import { Card } from './card';
import { CustomerGroupInfo } from './customerGroupInfo';
import { CustomerPreferences } from './customerPreferences';

/**
* Represents one of a business\'s customers, which can have one or more cards on file associated with it.
*/
export class Customer {
    /**
    * The customer\'s unique ID.
    */
    'id': string;
    /**
    * The time when the customer was created, in RFC 3339 format.
    */
    'createdAt': string;
    /**
    * The time when the customer was last updated, in RFC 3339 format.
    */
    'updatedAt': string;
    /**
    * The payment details of the customer\'s cards on file.
    */
    'cards'?: Array<Card>;
    /**
    * The customer\'s given (i.e., first) name.
    */
    'givenName'?: string;
    /**
    * The customer\'s family (i.e., last) name.
    */
    'familyName'?: string;
    /**
    * The customer\'s nickname.
    */
    'nickname'?: string;
    /**
    * The name of the customer\'s company.
    */
    'companyName'?: string;
    /**
    * The customer\'s email address.
    */
    'emailAddress'?: string;
    'address'?: Address;
    /**
    * The customer\'s phone number.
    */
    'phoneNumber'?: string;
    /**
    * The customer\'s birthday in RFC-3339 format. Year is optional, timezone and times are not allowed. Example: `0000-09-01T00:00:00-00:00` for a birthday on September 1st. `1998-09-01T00:00:00-00:00` for a birthday on September 1st 1998.
    */
    'birthday'?: string;
    /**
    * A second ID you can set to associate the customer with an entity in another system.
    */
    'referenceId'?: string;
    /**
    * A note to associate with the customer.
    */
    'note'?: string;
    'preferences'?: CustomerPreferences;
    /**
    * The groups the customer belongs to.
    */
    'groups'?: Array<CustomerGroupInfo>;
    /**
    * A creation source represents the method used to create the customer profile. See [CustomerCreationSource](#type-customercreationsource) for possible values
    */
    'creationSource'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "cards",
            "baseName": "cards",
            "type": "Array<Card>"
        },
        {
            "name": "givenName",
            "baseName": "given_name",
            "type": "string"
        },
        {
            "name": "familyName",
            "baseName": "family_name",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "company_name",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Address"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "birthday",
            "baseName": "birthday",
            "type": "string"
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "CustomerPreferences"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<CustomerGroupInfo>"
        },
        {
            "name": "creationSource",
            "baseName": "creation_source",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Customer.attributeTypeMap;
    }
}

