/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerFilter } from './customerFilter';
import { CustomerSort } from './customerSort';

/**
* Represents a query (filtering and sorting criteria) used to search for customer profiles.
*/
export class CustomerQuery {
    'filter'?: CustomerFilter;
    'sort'?: CustomerSort;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "CustomerFilter"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "CustomerSort"
        }    ];

    static getAttributeTypeMap() {
        return CustomerQuery.attributeTypeMap;
    }
}

