/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An employee created in the **Square Dashboard** account of a business.  Used by the Labor API.
*/
export class Employee {
    /**
    * UUID for this `Employee`.
    */
    'id'?: string;
    /**
    * Given (first) name of the employee.
    */
    'firstName'?: string;
    /**
    * Family (last) name of the employee
    */
    'lastName'?: string;
    /**
    * Email of the employee
    */
    'email'?: string;
    /**
    * Phone number of the employee in E.164 format, i.e. \"+12125554250\"
    */
    'phoneNumber'?: string;
    /**
    * A list of location IDs where this employee has access.
    */
    'locationIds'?: Array<string>;
    /**
    * Specifies the status of the employee being fetched. See [EmployeeStatus](#type-employeestatus) for possible values
    */
    'status'?: string;
    /**
    * A read-only timestamp in RFC 3339 format.
    */
    'createdAt'?: string;
    /**
    * A read-only timestamp in RFC 3339 format.
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "locationIds",
            "baseName": "location_ids",
            "type": "Array<string>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Employee.attributeTypeMap;
    }
}

