/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SourceApplication } from './sourceApplication';

/**
* Represents the transfer of a quantity of product inventory at a particular time from one location to another.
*/
export class InventoryTransfer {
    /**
    * A unique ID generated by Square for the [InventoryTransfer](#type-inventorytransfer).
    */
    'id'?: string;
    /**
    * An optional ID provided by the application to tie the [InventoryTransfer](#type-inventorytransfer) to an external system.
    */
    'referenceId'?: string;
    /**
    * The [InventoryState](#type-inventorystate) for the quantity of items being transfered. See [InventoryState](#type-inventorystate) for possible values
    */
    'state'?: string;
    /**
    * The Square ID of the [Location](#type-location) where the related quantity of items were tracked before the transfer.
    */
    'fromLocationId'?: string;
    /**
    * The Square ID of the [Location](#type-location) where the related quantity of items were tracked after the transfer.
    */
    'toLocationId'?: string;
    /**
    * The Square generated ID of the [CatalogObject](#type-catalogobject) being tracked.
    */
    'catalogObjectId'?: string;
    /**
    * The [CatalogObjectType](#type-catalogobjecttype) of the [CatalogObject](#type-catalogobject) being tracked.Tracking is only supported for the `ITEM_VARIATION` type.
    */
    'catalogObjectType'?: string;
    /**
    * The number of items affected by the transfer as a decimal string. Can support up to 5 digits after the decimal point.  _Important_: The Point of Sale app and Dashboard do not currently support decimal quantities. If a Point of Sale app or Dashboard attempts to read a decimal quantity on inventory counts or adjustments, the quantity will be rounded down to the nearest integer. For example, `2.5` will become `2`, and `-2.5` will become `-3`.  Read [Decimal Quantities (BETA)](/orders-api/what-it-does#decimal-quantities) for more information.
    */
    'quantity'?: string;
    /**
    * A client-generated timestamp in RFC 3339 format that indicates when the transfer took place. For write actions, the `occurred_at` timestamp cannot be older than 24 hours or in the future relative to the time of the request.
    */
    'occurredAt'?: string;
    /**
    * A read-only timestamp in RFC 3339 format that indicates when Square received the transfer request.
    */
    'createdAt'?: string;
    'source'?: SourceApplication;
    /**
    * The Square ID of the [Employee](#type-employee) responsible for the inventory transfer.
    */
    'employeeId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "fromLocationId",
            "baseName": "from_location_id",
            "type": "string"
        },
        {
            "name": "toLocationId",
            "baseName": "to_location_id",
            "type": "string"
        },
        {
            "name": "catalogObjectId",
            "baseName": "catalog_object_id",
            "type": "string"
        },
        {
            "name": "catalogObjectType",
            "baseName": "catalog_object_type",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string"
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SourceApplication"
        },
        {
            "name": "employeeId",
            "baseName": "employee_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InventoryTransfer.attributeTypeMap;
    }
}

