/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates the state of a tracked item quantity in the lifecycle of goods.
*/
export enum InventoryState {
    CUSTOM = <any> 'CUSTOM',
    IN_STOCK = <any> 'IN_STOCK',
    SOLD = <any> 'SOLD',
    RETURNED_BY_CUSTOMER = <any> 'RETURNED_BY_CUSTOMER',
    RESERVED_FOR_SALE = <any> 'RESERVED_FOR_SALE',
    SOLD_ONLINE = <any> 'SOLD_ONLINE',
    ORDERED_FROM_VENDOR = <any> 'ORDERED_FROM_VENDOR',
    RECEIVED_FROM_VENDOR = <any> 'RECEIVED_FROM_VENDOR',
    IN_TRANSIT_TO = <any> 'IN_TRANSIT_TO',
    NONE = <any> 'NONE',
    WASTE = <any> 'WASTE',
    UNLINKED_RETURN = <any> 'UNLINKED_RETURN'
}
