/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SourceApplication } from './sourceApplication';

/**
* Represents the quantity of an item variation that is physically present at a specific location, verified by a seller or a seller\'s employee. For example, a physical count might come from an employee counting the item variations on hand or from syncing with an external system.
*/
export class InventoryPhysicalCount {
    /**
    * A unique ID generated by Square for the [InventoryPhysicalCount](#type-inventoryphysicalcount).
    */
    'id'?: string;
    /**
    * An optional ID provided by the application to tie the [InventoryPhysicalCount](#type-inventoryphysicalcount) to an external system.
    */
    'referenceId'?: string;
    /**
    * The Square generated ID of the [CatalogObject](#type-catalogobject) being tracked.
    */
    'catalogObjectId'?: string;
    /**
    * The [CatalogObjectType](#type-catalogobjecttype) of the [CatalogObject](#type-catalogobject) being tracked. Tracking is only supported for the `ITEM_VARIATION` type.
    */
    'catalogObjectType'?: string;
    /**
    * The current [InventoryState](#type-inventorystate) for the related quantity of items. See [InventoryState](#type-inventorystate) for possible values
    */
    'state'?: string;
    /**
    * The Square ID of the [Location](#type-location) where the related quantity of items are being tracked.
    */
    'locationId'?: string;
    /**
    * The number of items affected by the physical count as a decimal string. Can support up to 5 digits after the decimal point.  _Important_: The Point of Sale app and Dashboard do not currently support decimal quantities. If a Point of Sale app or Dashboard attempts to read a decimal quantity on inventory counts or adjustments, the quantity will be rounded down to the nearest integer. For example, `2.5` will become `2`, and `-2.5` will become `-3`.  Read [Decimal Quantities (BETA)](/orders-api/what-it-does#decimal-quantities) for more information.
    */
    'quantity'?: string;
    'source'?: SourceApplication;
    /**
    * The Square ID of the [Employee](#type-employee) responsible for the physical count.
    */
    'employeeId'?: string;
    /**
    * A client-generated timestamp in RFC 3339 format that indicates when the physical count took place. For write actions, the `occurred_at` timestamp cannot be older than 24 hours or in the future relative to the time of the request.
    */
    'occurredAt'?: string;
    /**
    * A read-only timestamp in RFC 3339 format that indicates when Square received the physical count.
    */
    'createdAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string"
        },
        {
            "name": "catalogObjectId",
            "baseName": "catalog_object_id",
            "type": "string"
        },
        {
            "name": "catalogObjectType",
            "baseName": "catalog_object_type",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SourceApplication"
        },
        {
            "name": "employeeId",
            "baseName": "employee_id",
            "type": "string"
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InventoryPhysicalCount.attributeTypeMap;
    }
}

