/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates the state of a tracked item quantity in the lifecycle of goods.
*/
export enum InventoryState {
    CUSTOM = <any> 'CUSTOM',
    INSTOCK = <any> 'IN_STOCK',
    SOLD = <any> 'SOLD',
    RETURNEDBYCUSTOMER = <any> 'RETURNED_BY_CUSTOMER',
    RESERVEDFORSALE = <any> 'RESERVED_FOR_SALE',
    SOLDONLINE = <any> 'SOLD_ONLINE',
    ORDEREDFROMVENDOR = <any> 'ORDERED_FROM_VENDOR',
    RECEIVEDFROMVENDOR = <any> 'RECEIVED_FROM_VENDOR',
    INTRANSITTO = <any> 'IN_TRANSIT_TO',
    NONE = <any> 'NONE',
    WASTE = <any> 'WASTE',
    UNLINKEDRETURN = <any> 'UNLINKED_RETURN'
}
