/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from './money';

/**
* Price and inventory alerting overrides for a [CatalogItemVariation](#type-catalogitemvariation) at a specific [location](#type-location).
*/
export class ItemVariationLocationOverrides {
    /**
    * The ID of the [location](#type-location).
    */
    'locationId'?: string;
    'priceMoney'?: Money;
    /**
    * The pricing type (fixed or variable) for the [CatalogItemVariation](#type-catalogitemvariation) at the given [location](#type-location). See [CatalogPricingType](#type-catalogpricingtype) for possible values
    */
    'pricingType'?: string;
    /**
    * If `true`, inventory tracking is active for the [CatalogItemVariation](#type-catalogitemvariation) at this [location](#type-location).
    */
    'trackInventory'?: boolean;
    /**
    * Indicates whether the [CatalogItemVariation](#type-catalogitemvariation) displays an alert when its inventory quantity is less than or equal to its `inventory_alert_threshold`. See [InventoryAlertType](#type-inventoryalerttype) for possible values
    */
    'inventoryAlertType'?: string;
    /**
    * If the inventory quantity for the variation is less than or equal to this value and `inventory_alert_type` is `LOW_QUANTITY`, the variation displays an alert in the merchant dashboard.  This value is always an integer.
    */
    'inventoryAlertThreshold'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        },
        {
            "name": "priceMoney",
            "baseName": "price_money",
            "type": "Money"
        },
        {
            "name": "pricingType",
            "baseName": "pricing_type",
            "type": "string"
        },
        {
            "name": "trackInventory",
            "baseName": "track_inventory",
            "type": "boolean"
        },
        {
            "name": "inventoryAlertType",
            "baseName": "inventory_alert_type",
            "type": "string"
        },
        {
            "name": "inventoryAlertThreshold",
            "baseName": "inventory_alert_threshold",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ItemVariationLocationOverrides.attributeTypeMap;
    }
}

