/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A request for a filtered set of `BreakType` objects
*/
export class ListBreakTypesRequest {
    /**
    * Filter Break Types returned to only those that are associated with the specified location.
    */
    'locationId'?: string;
    /**
    * Maximum number of Break Types to return per page. Can range between 1 and 200. The default is the maximum at 200.
    */
    'limit'?: number;
    /**
    * Pointer to the next page of Break Type results to fetch.
    */
    'cursor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListBreakTypesRequest.attributeTypeMap;
    }
}

