/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SquareError } from './squareError';
import { WorkweekConfig } from './workweekConfig';

/**
* The response to a request for a set of `WorkweekConfig` objects. Contains the requested `WorkweekConfig` objects. May contain a set of `SquareError` objects if the request resulted in errors.
*/
export class ListWorkweekConfigsResponse {
    /**
    * A page of Employee Wage results.
    */
    'workweekConfigs'?: Array<WorkweekConfig>;
    /**
    * Value supplied in the subsequent request to fetch the next page of Employee Wage results.
    */
    'cursor'?: string;
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<SquareError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workweekConfigs",
            "baseName": "workweek_configs",
            "type": "Array<WorkweekConfig>"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        }    ];

    static getAttributeTypeMap() {
        return ListWorkweekConfigsResponse.attributeTypeMap;
    }
}

