/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BreakType } from './breakType';
import { SquareError } from './squareError';

/**
* The response to a request for a set of `BreakTypes`. Contains the requested `BreakType` objects. May contain a set of `SquareError` objects if the request resulted in errors.
*/
export class ListBreakTypesResponse {
    /**
    *  A page of `BreakType` results.
    */
    'breakTypes'?: Array<BreakType>;
    /**
    * Value supplied in the subsequent request to fetch the next next page of Break Type results.
    */
    'cursor'?: string;
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<SquareError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "breakTypes",
            "baseName": "break_types",
            "type": "Array<BreakType>"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        }    ];

    static getAttributeTypeMap() {
        return ListBreakTypesResponse.attributeTypeMap;
    }
}

