/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A request for a set of `EmployeeWage` objects
*/
export class ListEmployeeWagesRequest {
    /**
    * Filter wages returned to only those that are associated with the specified employee.
    */
    'employeeId'?: string;
    /**
    * Maximum number of Employee Wages to return per page. Can range between 1 and 200. The default is the maximum at 200.
    */
    'limit'?: number;
    /**
    * Pointer to the next page of Employee Wage results to fetch.
    */
    'cursor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employeeId",
            "baseName": "employee_id",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListEmployeeWagesRequest.attributeTypeMap;
    }
}

