/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Unit of area used to measure a quantity.
*/
export enum MeasurementUnitArea {
    IMPERIALACRE = <any> 'IMPERIAL_ACRE',
    IMPERIALSQUAREINCH = <any> 'IMPERIAL_SQUARE_INCH',
    IMPERIALSQUAREFOOT = <any> 'IMPERIAL_SQUARE_FOOT',
    IMPERIALSQUAREYARD = <any> 'IMPERIAL_SQUARE_YARD',
    IMPERIALSQUAREMILE = <any> 'IMPERIAL_SQUARE_MILE',
    METRICSQUARECENTIMETER = <any> 'METRIC_SQUARE_CENTIMETER',
    METRICSQUAREMETER = <any> 'METRIC_SQUARE_METER',
    METRICSQUAREKILOMETER = <any> 'METRIC_SQUARE_KILOMETER'
}
