/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Unit of weight used to measure a quantity.
*/
export enum MeasurementUnitWeight {
    IMPERIALWEIGHTOUNCE = <any> 'IMPERIAL_WEIGHT_OUNCE',
    IMPERIALPOUND = <any> 'IMPERIAL_POUND',
    IMPERIALSTONE = <any> 'IMPERIAL_STONE',
    METRICMILLIGRAM = <any> 'METRIC_MILLIGRAM',
    METRICGRAM = <any> 'METRIC_GRAM',
    METRICKILOGRAM = <any> 'METRIC_KILOGRAM'
}
