/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementUnitCustom } from './measurementUnitCustom';

/**
* Represents a unit of measurement to use with a quantity, such as ounces or inches. Exactly one of the following fields are required: `custom_unit`, `area_unit`, `length_unit`, `volume_unit`, and `weight_unit`.  The `family` field describes the type of measurement. For example, ounces are in the weight family.
*/
export class MeasurementUnit {
    'customUnit'?: MeasurementUnitCustom;
    /**
    * Represents a standard area unit. See [MeasurementUnitArea](#type-measurementunitarea) for possible values
    */
    'areaUnit'?: string;
    /**
    * Represents a standard length unit. See [MeasurementUnitLength](#type-measurementunitlength) for possible values
    */
    'lengthUnit'?: string;
    /**
    * Represents a standard volume unit. See [MeasurementUnitVolume](#type-measurementunitvolume) for possible values
    */
    'volumeUnit'?: string;
    /**
    * Represents a standard unit of weight or mass. See [MeasurementUnitWeight](#type-measurementunitweight) for possible values
    */
    'weightUnit'?: string;
    /**
    * Reserved for API integrations that lack the ability to specify a real measurement unit See [MeasurementUnitGeneric](#type-measurementunitgeneric) for possible values
    */
    'genericUnit'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customUnit",
            "baseName": "custom_unit",
            "type": "MeasurementUnitCustom"
        },
        {
            "name": "areaUnit",
            "baseName": "area_unit",
            "type": "string"
        },
        {
            "name": "lengthUnit",
            "baseName": "length_unit",
            "type": "string"
        },
        {
            "name": "volumeUnit",
            "baseName": "volume_unit",
            "type": "string"
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string"
        },
        {
            "name": "genericUnit",
            "baseName": "generic_unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MeasurementUnit.attributeTypeMap;
    }
}

