/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The unit of volume used to measure a quantity.
*/
export enum MeasurementUnitVolume {
    GENERIC_FLUID_OUNCE = <any> 'GENERIC_FLUID_OUNCE',
    GENERIC_SHOT = <any> 'GENERIC_SHOT',
    GENERIC_CUP = <any> 'GENERIC_CUP',
    GENERIC_PINT = <any> 'GENERIC_PINT',
    GENERIC_QUART = <any> 'GENERIC_QUART',
    GENERIC_GALLON = <any> 'GENERIC_GALLON',
    IMPERIAL_CUBIC_INCH = <any> 'IMPERIAL_CUBIC_INCH',
    IMPERIAL_CUBIC_FOOT = <any> 'IMPERIAL_CUBIC_FOOT',
    IMPERIAL_CUBIC_YARD = <any> 'IMPERIAL_CUBIC_YARD',
    METRIC_MILLILITER = <any> 'METRIC_MILLILITER',
    METRIC_LITER = <any> 'METRIC_LITER'
}
