/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Unit of weight used to measure a quantity.
*/
export enum MeasurementUnitWeight {
    IMPERIAL_WEIGHT_OUNCE = <any> 'IMPERIAL_WEIGHT_OUNCE',
    IMPERIAL_POUND = <any> 'IMPERIAL_POUND',
    IMPERIAL_STONE = <any> 'IMPERIAL_STONE',
    METRIC_MILLIGRAM = <any> 'METRIC_MILLIGRAM',
    METRIC_GRAM = <any> 'METRIC_GRAM',
    METRIC_KILOGRAM = <any> 'METRIC_KILOGRAM'
}
