/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The recipient of a fulfillment.
*/
export class OrderFulfillmentRecipient {
    /**
    * The Customer ID of the customer associated with the fulfillment.  If customer_id is provided, the corresponding recipient information fields (`display_name`, `email_address`, and `phone_number`) are automatically populated from the relevant customer profile. If the targeted profile information does not contain the necessary required information, the request will result in an error.
    */
    'customerId'?: string;
    /**
    * The display name of the fulfillment recipient.  If provided, overrides the value from customer profile indicated by customer_id.
    */
    'displayName'?: string;
    /**
    * The email address of the fulfillment recipient.  If provided, overrides the value from customer profile indicated by customer_id.
    */
    'emailAddress'?: string;
    /**
    * The phone number of the fulfillment recipient.  If provided, overrides the value from customer profile indicated by customer_id.
    */
    'phoneNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrderFulfillmentRecipient.attributeTypeMap;
    }
}

