/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates whether this is a line item or order level discount.
*/
export enum OrderLineItemDiscountScope {
    OTHERDISCOUNTSCOPE = <any> 'OTHER_DISCOUNT_SCOPE',
    LINEITEM = <any> 'LINE_ITEM',
    ORDER = <any> 'ORDER'
}
