/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from './money';
import { OrderQuantityUnit } from './orderQuantityUnit';
import { OrderReturnDiscount } from './orderReturnDiscount';
import { OrderReturnLineItemModifier } from './orderReturnLineItemModifier';
import { OrderReturnTax } from './orderReturnTax';

/**
* The line item being returned in an Order.
*/
export class OrderReturnLineItem {
    /**
    * Unique identifier for this return line item entry. This is a read-only field.
    */
    'uid'?: string;
    /**
    * `uid` of the LineItem in the original sale Order.
    */
    'sourceLineItemUid'?: string;
    /**
    * The name of the line item.
    */
    'name'?: string;
    /**
    * The quantity returned, formatted as a decimal number. For example: `\"3\"`.  Line items with a `quantity_unit` can have non-integer quantities. For example: `\"1.70000\"`.
    */
    'quantity': string;
    'quantityUnit'?: OrderQuantityUnit;
    /**
    * The note of the returned line item.
    */
    'note'?: string;
    /**
    * The [CatalogItemVariation](#type-catalogitemvariation) id applied to this returned line item.
    */
    'catalogObjectId'?: string;
    /**
    * The name of the variation applied to this returned line item.
    */
    'variationName'?: string;
    /**
    * The [CatalogModifier](#type-catalogmodifier)s applied to this line item.
    */
    'returnModifiers'?: Array<OrderReturnLineItemModifier>;
    /**
    * A list of taxes applied to this line item. On read or retrieve, this list includes both item-level taxes and any return-level taxes apportioned to this item.
    */
    'returnTaxes'?: Array<OrderReturnTax>;
    /**
    * A list of discounts applied to this line item. On read or retrieve, this list includes both item-level discounts and any return-level discounts apportioned to this item.
    */
    'returnDiscounts'?: Array<OrderReturnDiscount>;
    'basePriceMoney'?: Money;
    'variationTotalPriceMoney'?: Money;
    'grossReturnMoney'?: Money;
    'totalTaxMoney'?: Money;
    'totalDiscountMoney'?: Money;
    'totalMoney'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "sourceLineItemUid",
            "baseName": "source_line_item_uid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string"
        },
        {
            "name": "quantityUnit",
            "baseName": "quantity_unit",
            "type": "OrderQuantityUnit"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "catalogObjectId",
            "baseName": "catalog_object_id",
            "type": "string"
        },
        {
            "name": "variationName",
            "baseName": "variation_name",
            "type": "string"
        },
        {
            "name": "returnModifiers",
            "baseName": "return_modifiers",
            "type": "Array<OrderReturnLineItemModifier>"
        },
        {
            "name": "returnTaxes",
            "baseName": "return_taxes",
            "type": "Array<OrderReturnTax>"
        },
        {
            "name": "returnDiscounts",
            "baseName": "return_discounts",
            "type": "Array<OrderReturnDiscount>"
        },
        {
            "name": "basePriceMoney",
            "baseName": "base_price_money",
            "type": "Money"
        },
        {
            "name": "variationTotalPriceMoney",
            "baseName": "variation_total_price_money",
            "type": "Money"
        },
        {
            "name": "grossReturnMoney",
            "baseName": "gross_return_money",
            "type": "Money"
        },
        {
            "name": "totalTaxMoney",
            "baseName": "total_tax_money",
            "type": "Money"
        },
        {
            "name": "totalDiscountMoney",
            "baseName": "total_discount_money",
            "type": "Money"
        },
        {
            "name": "totalMoney",
            "baseName": "total_money",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return OrderReturnLineItem.attributeTypeMap;
    }
}

