/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from './money';

/**
* A [CatalogModifier](#type-catalogmodifier).
*/
export class OrderLineItemModifier {
    /**
    * Unique ID that identifies the modifier only within this order.  This field is read-only.
    */
    'uid'?: string;
    /**
    * The catalog object id referencing [CatalogModifier](#type-catalogmodifier).
    */
    'catalogObjectId'?: string;
    /**
    * The name of the item modifier.
    */
    'name'?: string;
    'basePriceMoney'?: Money;
    'totalPriceMoney'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string"
        },
        {
            "name": "catalogObjectId",
            "baseName": "catalog_object_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "basePriceMoney",
            "baseName": "base_price_money",
            "type": "Money"
        },
        {
            "name": "totalPriceMoney",
            "baseName": "total_price_money",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return OrderLineItemModifier.attributeTypeMap;
    }
}

