/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Defines the parameters that can be included in the body of a request to the RegisterDomain endpoint.
*/
export class RegisterDomainRequest {
    /**
    * A domain name as described in RFC-1034 that will be registered with ApplePay
    */
    'domainName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "domainName",
            "baseName": "domain_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegisterDomainRequest.attributeTypeMap;
    }
}

