/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogObject } from './catalogObject';
import { SquareError } from './squareError';

/**
* 
*/
export class RetrieveCatalogObjectResponse {
    /**
    * The set of [SquareError](#type-squareerror)s encountered.
    */
    'errors'?: Array<SquareError>;
    'object'?: CatalogObject;
    /**
    * A list of [CatalogObject](#type-catalogobject)s referenced by the object in the `object` field.
    */
    'relatedObjects'?: Array<CatalogObject>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "CatalogObject"
        },
        {
            "name": "relatedObjects",
            "baseName": "related_objects",
            "type": "Array<CatalogObject>"
        }    ];

    static getAttributeTypeMap() {
        return RetrieveCatalogObjectResponse.attributeTypeMap;
    }
}

