/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InventoryAdjustment } from './inventoryAdjustment';

/**
* 
*/
export class RetrieveInventoryAdjustmentResponse {
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<Error>;
    'adjustment'?: InventoryAdjustment;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Error>"
        },
        {
            "name": "adjustment",
            "baseName": "adjustment",
            "type": "InventoryAdjustment"
        }    ];

    static getAttributeTypeMap() {
        return RetrieveInventoryAdjustmentResponse.attributeTypeMap;
    }
}

