/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Order } from './order';
import { OrderEntry } from './orderEntry';
import { SquareError } from './squareError';

/**
* Only one of `order_entries` or `orders` fields will be set, depending on whether `return_entries` was set on the [SearchOrdersRequest](#type-searchorderrequest).
*/
export class SearchOrdersResponse {
    /**
    * List of [OrderEntries](#type-orderentry) that fit the query conditions.  Populated only if `order_entries` was set to `true` in the request.
    */
    'orderEntries'?: Array<OrderEntry>;
    /**
    * List of [Orders](#type-order) that match query conditions. Populated only if `return_entries` in the request is set to `false`.
    */
    'orders'?: Array<Order>;
    /**
    * The pagination cursor to be used in a subsequent request. If unset, this is the final response. See [Pagination](/basics/api101/pagination) for more information.
    */
    'cursor'?: string;
    /**
    * [Errors](#type-error) encountered during the search.
    */
    'errors'?: Array<SquareError>;
    /**
    * List of transaction IDs identifying transactions that could not be converted to an `Order`. Empty if `return_entries` is true, however, attempts to retrieve those orders may encounter subsequent `unconvertible_transcation_ids` Note that this field will not be present after SearchOrders moves from BETA to GA.
    */
    'unconvertibleTransactionIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderEntries",
            "baseName": "order_entries",
            "type": "Array<OrderEntry>"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<Order>"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        },
        {
            "name": "unconvertibleTransactionIds",
            "baseName": "unconvertible_transaction_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return SearchOrdersResponse.attributeTypeMap;
    }
}

