/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Shift } from './shift';
import { SquareError } from './squareError';

/**
* The response to a request for `Shift` objects. Contains the requested `Shift` objects. May contain a set of `SquareError` objects if the request resulted in errors.
*/
export class SearchShiftsResponse {
    /**
    * Shifts
    */
    'shifts'?: Array<Shift>;
    /**
    * Opaque cursor for fetching the next page.
    */
    'cursor'?: string;
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<SquareError>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shifts",
            "baseName": "shifts",
            "type": "Array<Shift>"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SquareError>"
        }    ];

    static getAttributeTypeMap() {
        return SearchShiftsResponse.attributeTypeMap;
    }
}

