/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShiftQuery } from './shiftQuery';

/**
* A request for a filtered and sorted set of `Shift` objects.
*/
export class SearchShiftsRequest {
    'query'?: ShiftQuery;
    /**
    * number of resources in a page (200 by default).
    */
    'limit'?: number;
    /**
    * opaque cursor for fetching the next page.
    */
    'cursor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "ShiftQuery"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SearchShiftsRequest.attributeTypeMap;
    }
}

