/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DateRange } from './dateRange';

/**
* A `Shift` search query filter parameter that sets a range of days that  a `Shift` must start or end in before passing the filter condition.
*/
export class ShiftWorkday {
    'dateRange'?: DateRange;
    /**
    * The strategy on which the dates are applied. See [ShiftWorkdayMatcher](#type-shiftworkdaymatcher) for possible values
    */
    'matchShiftsBy'?: string;
    /**
    * Location-specific timezones convert workdays to datetime filters. Every location included in the query must have a timezone, or this field must be provided as a fallback. Format: the IANA timezone database identifier for the relevant timezone.
    */
    'defaultTimezone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateRange",
            "baseName": "date_range",
            "type": "DateRange"
        },
        {
            "name": "matchShiftsBy",
            "baseName": "match_shifts_by",
            "type": "string"
        },
        {
            "name": "defaultTimezone",
            "baseName": "default_timezone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ShiftWorkday.attributeTypeMap;
    }
}

