/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from './money';

/**
* The hourly wage rate used to compensate an employee for this shift.
*/
export class ShiftWage {
    /**
    * The name of the job performed during this shift. Square labor-reporting UIs may group shifts together by title.
    */
    'title'?: string;
    'hourlyRate'?: Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "hourlyRate",
            "baseName": "hourly_rate",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return ShiftWage.attributeTypeMap;
    }
}

