/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShiftFilter } from './shiftFilter';
import { ShiftSort } from './shiftSort';

/**
* The parameters of a `Shift` search query. Includes filter and sort options.
*/
export class ShiftQuery {
    'filter'?: ShiftFilter;
    'sort'?: ShiftSort;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ShiftFilter"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "ShiftSort"
        }    ];

    static getAttributeTypeMap() {
        return ShiftQuery.attributeTypeMap;
    }
}

