/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StandardUnitDescription } from './standardUnitDescription';

/**
* Group of standard measurement units.
*/
export class StandardUnitDescriptionGroup {
    /**
    * List of measurement units in this description group.
    */
    'standardUnitDescriptions'?: Array<StandardUnitDescription>;
    /**
    * IETF language tag.
    */
    'languageCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "standardUnitDescriptions",
            "baseName": "standard_unit_descriptions",
            "type": "Array<StandardUnitDescription>"
        },
        {
            "name": "languageCode",
            "baseName": "language_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StandardUnitDescriptionGroup.attributeTypeMap;
    }
}

