/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalRecipient } from './additionalRecipient';
import { Money } from './money';
import { TenderCardDetails } from './tenderCardDetails';
import { TenderCashDetails } from './tenderCashDetails';

/**
* Represents a tender (i.e., a method of payment) used in a Square transaction.
*/
export class Tender {
    /**
    * The tender\'s unique ID.
    */
    'id'?: string;
    /**
    * The ID of the transaction\'s associated location.
    */
    'locationId'?: string;
    /**
    * The ID of the tender\'s associated transaction.
    */
    'transactionId'?: string;
    /**
    * The time when the tender was created, in RFC 3339 format.
    */
    'createdAt'?: string;
    /**
    * An optional note associated with the tender at the time of payment.
    */
    'note'?: string;
    'amountMoney'?: Money;
    'tipMoney'?: Money;
    'processingFeeMoney'?: Money;
    /**
    * If the tender is associated with a customer or represents a customer\'s card on file, this is the ID of the associated customer.
    */
    'customerId'?: string;
    /**
    * The type of tender, such as `CARD` or `CASH`. See [TenderType](#type-tendertype) for possible values
    */
    'type': string;
    'cardDetails'?: TenderCardDetails;
    'cashDetails'?: TenderCashDetails;
    /**
    * Additional recipients (other than the merchant) receiving a portion of this tender. For example, fees assessed on the purchase by a third party integration.
    */
    'additionalRecipients'?: Array<AdditionalRecipient>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string"
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "amountMoney",
            "baseName": "amount_money",
            "type": "Money"
        },
        {
            "name": "tipMoney",
            "baseName": "tip_money",
            "type": "Money"
        },
        {
            "name": "processingFeeMoney",
            "baseName": "processing_fee_money",
            "type": "Money"
        },
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "cardDetails",
            "baseName": "card_details",
            "type": "TenderCardDetails"
        },
        {
            "name": "cashDetails",
            "baseName": "cash_details",
            "type": "TenderCashDetails"
        },
        {
            "name": "additionalRecipients",
            "baseName": "additional_recipients",
            "type": "Array<AdditionalRecipient>"
        }    ];

    static getAttributeTypeMap() {
        return Tender.attributeTypeMap;
    }
}

