/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Indicates the Square product used to process a transaction.
*/
export enum TransactionProduct {
    REGISTER = <any> 'REGISTER',
    EXTERNALAPI = <any> 'EXTERNAL_API',
    BILLING = <any> 'BILLING',
    APPOINTMENTS = <any> 'APPOINTMENTS',
    INVOICES = <any> 'INVOICES',
    ONLINESTORE = <any> 'ONLINE_STORE',
    PAYROLL = <any> 'PAYROLL',
    OTHER = <any> 'OTHER'
}
