/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class UpdateItemTaxesRequest {
    /**
    * The [CatalogItem](#type-catalogitem)s whose enabled/disabled [CatalogTax](#type-catalogtax)es are being updated.
    */
    'itemIds': Array<string>;
    /**
    * The set of [CatalogTax](#type-catalogtax)es (referenced by ID) to enable for the [CatalogItem](#type-catalogitem).
    */
    'taxesToEnable'?: Array<string>;
    /**
    * The set of [CatalogTax](#type-catalogtax)es (referenced by ID) to disable for the [CatalogItem](#type-catalogitem).
    */
    'taxesToDisable'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemIds",
            "baseName": "item_ids",
            "type": "Array<string>"
        },
        {
            "name": "taxesToEnable",
            "baseName": "taxes_to_enable",
            "type": "Array<string>"
        },
        {
            "name": "taxesToDisable",
            "baseName": "taxes_to_disable",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateItemTaxesRequest.attributeTypeMap;
    }
}

