/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Customer } from './customer';

/**
* Defines the fields that are included in the response body of a request to the UpdateCustomer endpoint.  One of `errors` or `customer` is present in a given response (never both).
*/
export class UpdateCustomerResponse {
    /**
    * Any errors that occurred during the request.
    */
    'errors'?: Array<Error>;
    'customer'?: Customer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Error>"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "Customer"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCustomerResponse.attributeTypeMap;
    }
}

