/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class UpdateItemModifierListsRequest {
    /**
    * The [CatalogItem](#type-catalogitem)s whose [CatalogModifierList](#type-catalogmodifierlist)s are being updated.
    */
    'itemIds': Array<string>;
    /**
    * The set of [CatalogModifierList](#type-catalogmodifierlist)s (referenced by ID) to enable for the [CatalogItem](#type-catalogitem).
    */
    'modifierListsToEnable'?: Array<string>;
    /**
    * The set of [CatalogModifierList](#type-catalogmodifierlist)s (referenced by ID) to disable for the [CatalogItem](#type-catalogitem).
    */
    'modifierListsToDisable'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemIds",
            "baseName": "item_ids",
            "type": "Array<string>"
        },
        {
            "name": "modifierListsToEnable",
            "baseName": "modifier_lists_to_enable",
            "type": "Array<string>"
        },
        {
            "name": "modifierListsToDisable",
            "baseName": "modifier_lists_to_disable",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateItemModifierListsRequest.attributeTypeMap;
    }
}

