/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './address';

/**
* Defines the body parameters that can be provided in a request to the UpdateCustomer endpoint.
*/
export class UpdateCustomerRequest {
    /**
    * The customer\'s given (i.e., first) name.
    */
    'givenName'?: string;
    /**
    * The customer\'s family (i.e., last) name.
    */
    'familyName'?: string;
    /**
    * The name of the customer\'s company.
    */
    'companyName'?: string;
    /**
    * A nickname for the customer.
    */
    'nickname'?: string;
    /**
    * The customer\'s email address.
    */
    'emailAddress'?: string;
    'address'?: Address;
    /**
    * The customer\'s phone number.
    */
    'phoneNumber'?: string;
    /**
    * An optional second ID you can set to associate the customer with an entity in another system.
    */
    'referenceId'?: string;
    /**
    * An optional note to associate with the customer.
    */
    'note'?: string;
    /**
    * The customer birthday in RFC-3339 format. Year is optional, timezone and times are not allowed. Example: `0000-09-01T00:00:00-00:00` for a birthday on September 1st. `1998-09-01T00:00:00-00:00` for a birthday on September 1st 1998.
    */
    'birthday'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "givenName",
            "baseName": "given_name",
            "type": "string"
        },
        {
            "name": "familyName",
            "baseName": "family_name",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "company_name",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Address"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "referenceId",
            "baseName": "reference_id",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "birthday",
            "baseName": "birthday",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCustomerRequest.attributeTypeMap;
    }
}

