/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BreakType } from './breakType';

/**
* A request to update a `BreakType`
*/
export class UpdateBreakTypeRequest {
    'breakType'?: BreakType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "breakType",
            "baseName": "break_type",
            "type": "BreakType"
        }    ];

    static getAttributeTypeMap() {
        return UpdateBreakTypeRequest.attributeTypeMap;
    }
}

