/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Money } from './v1Money';

/**
* V1CashDrawerEvent
*/
export class V1CashDrawerEvent {
    /**
    * The event\'s unique ID.
    */
    'id'?: string;
    /**
    * The ID of the employee that created the event.
    */
    'employeeId'?: string;
    /**
    * The type of event that occurred. See [V1CashDrawerEventEventType](#type-v1cashdrawereventeventtype) for possible values
    */
    'eventType'?: string;
    'eventMoney'?: V1Money;
    /**
    * The time when the event occurred, in ISO 8601 format.
    */
    'createdAt'?: string;
    /**
    * An optional description of the event, entered by the employee that created it.
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "employeeId",
            "baseName": "employee_id",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "string"
        },
        {
            "name": "eventMoney",
            "baseName": "event_money",
            "type": "V1Money"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1CashDrawerEvent.attributeTypeMap;
    }
}

