/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* V1Category
*/
export class V1Category {
    /**
    * The category\'s unique ID.
    */
    'id'?: string;
    /**
    * The category\'s name.
    */
    'name'?: string;
    /**
    * The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
    */
    'v2Id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "v2Id",
            "baseName": "v2_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1Category.attributeTypeMap;
    }
}

