/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1CashDrawerEventEventType {
    NOSALE = <any> 'NO_SALE',
    CASHTENDERPAYMENT = <any> 'CASH_TENDER_PAYMENT',
    OTHERTENDERPAYMENT = <any> 'OTHER_TENDER_PAYMENT',
    CASHTENDERCANCELEDPAYMENT = <any> 'CASH_TENDER_CANCELED_PAYMENT',
    OTHERTENDERCANCELEDPAYMENT = <any> 'OTHER_TENDER_CANCELED_PAYMENT',
    CASHTENDERREFUND = <any> 'CASH_TENDER_REFUND',
    OTHERTENDERREFUND = <any> 'OTHER_TENDER_REFUND',
    PAIDIN = <any> 'PAID_IN',
    PAIDOUT = <any> 'PAID_OUT'
}
