/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Device } from './device';
import { V1CashDrawerEvent } from './v1CashDrawerEvent';
import { V1Money } from './v1Money';

/**
* Contains details for a single cash drawer shift.
*/
export class V1CashDrawerShift {
    /**
    * The shift\'s unique ID.
    */
    'id'?: string;
    /**
    * The shift\'s current state. See [V1CashDrawerShiftEventType](#type-v1cashdrawershifteventtype) for possible values
    */
    'eventType'?: string;
    /**
    * The time when the shift began, in ISO 8601 format.
    */
    'openedAt'?: string;
    /**
    * The time when the shift ended, in ISO 8601 format.
    */
    'endedAt'?: string;
    /**
    * The time when the shift was closed, in ISO 8601 format.
    */
    'closedAt'?: string;
    /**
    * The IDs of all employees that were logged into Square Register at some point during the cash drawer shift.
    */
    'employeeIds'?: Array<string>;
    /**
    * The ID of the employee that started the cash drawer shift.
    */
    'openingEmployeeId'?: string;
    /**
    * The ID of the employee that ended the cash drawer shift.
    */
    'endingEmployeeId'?: string;
    /**
    * The ID of the employee that closed the cash drawer shift by auditing the cash drawer\'s contents.
    */
    'closingEmployeeId'?: string;
    /**
    * A description of the cash drawer shift.
    */
    'description'?: string;
    'startingCashMoney'?: V1Money;
    'cashPaymentMoney'?: V1Money;
    'cashRefundsMoney'?: V1Money;
    'cashPaidInMoney'?: V1Money;
    'cashPaidOutMoney'?: V1Money;
    'expectedCashMoney'?: V1Money;
    'closedCashMoney'?: V1Money;
    'device'?: Device;
    /**
    * All of the events (payments, refunds, and so on) that involved the cash drawer during the shift.
    */
    'events'?: Array<V1CashDrawerEvent>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "string"
        },
        {
            "name": "openedAt",
            "baseName": "opened_at",
            "type": "string"
        },
        {
            "name": "endedAt",
            "baseName": "ended_at",
            "type": "string"
        },
        {
            "name": "closedAt",
            "baseName": "closed_at",
            "type": "string"
        },
        {
            "name": "employeeIds",
            "baseName": "employee_ids",
            "type": "Array<string>"
        },
        {
            "name": "openingEmployeeId",
            "baseName": "opening_employee_id",
            "type": "string"
        },
        {
            "name": "endingEmployeeId",
            "baseName": "ending_employee_id",
            "type": "string"
        },
        {
            "name": "closingEmployeeId",
            "baseName": "closing_employee_id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "startingCashMoney",
            "baseName": "starting_cash_money",
            "type": "V1Money"
        },
        {
            "name": "cashPaymentMoney",
            "baseName": "cash_payment_money",
            "type": "V1Money"
        },
        {
            "name": "cashRefundsMoney",
            "baseName": "cash_refunds_money",
            "type": "V1Money"
        },
        {
            "name": "cashPaidInMoney",
            "baseName": "cash_paid_in_money",
            "type": "V1Money"
        },
        {
            "name": "cashPaidOutMoney",
            "baseName": "cash_paid_out_money",
            "type": "V1Money"
        },
        {
            "name": "expectedCashMoney",
            "baseName": "expected_cash_money",
            "type": "V1Money"
        },
        {
            "name": "closedCashMoney",
            "baseName": "closed_cash_money",
            "type": "V1Money"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "Device"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<V1CashDrawerEvent>"
        }    ];

    static getAttributeTypeMap() {
        return V1CashDrawerShift.attributeTypeMap;
    }
}

