/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1EmployeeRole } from './v1EmployeeRole';

/**
* 
*/
export class V1CreateEmployeeRoleRequest {
    'employeeRole'?: V1EmployeeRole;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employeeRole",
            "baseName": "employee_role",
            "type": "V1EmployeeRole"
        }    ];

    static getAttributeTypeMap() {
        return V1CreateEmployeeRoleRequest.attributeTypeMap;
    }
}

