/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1DiscountColor {
    _9da2a6 = <any> '9da2a6',
    _4ab200 = <any> '4ab200',
    _0b8000 = <any> '0b8000',
    _2952cc = <any> '2952cc',
    A82ee5 = <any> 'a82ee5',
    E5457a = <any> 'e5457a',
    B21212 = <any> 'b21212',
    _593c00 = <any> '593c00',
    E5BF00 = <any> 'e5BF00'
}
