/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represents one of a business\'s employees.
*/
export class V1Employee {
    /**
    * The employee\'s unique ID.
    */
    'id'?: string;
    /**
    * The employee\'s first name.
    */
    'firstName': string;
    /**
    * The employee\'s last name.
    */
    'lastName': string;
    /**
    * The ids of the employee\'s associated roles. Currently, you can specify only one or zero roles per employee.
    */
    'roleIds'?: Array<string>;
    /**
    * The IDs of the locations the employee is allowed to clock in at.
    */
    'authorizedLocationIds'?: Array<string>;
    /**
    * The employee\'s email address.
    */
    'email'?: string;
    /**
    * CWhether the employee is ACTIVE or INACTIVE. Inactive employees cannot sign in to Square Register.Merchants update this field from the Square Dashboard. See [V1EmployeeStatus](#type-v1employeestatus) for possible values
    */
    'status'?: string;
    /**
    * An ID the merchant can set to associate the employee with an entity in another system.
    */
    'externalId'?: string;
    /**
    * The time when the employee entity was created, in ISO 8601 format.
    */
    'createdAt'?: string;
    /**
    * The time when the employee entity was most recently updated, in ISO 8601 format.
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "roleIds",
            "baseName": "role_ids",
            "type": "Array<string>"
        },
        {
            "name": "authorizedLocationIds",
            "baseName": "authorized_location_ids",
            "type": "Array<string>"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1Employee.attributeTypeMap;
    }
}

