/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1EmployeeRolePermissions {
    ACCESS_SALES_HISTORY = <any> 'REGISTER_ACCESS_SALES_HISTORY',
    APPLY_RESTRICTED_DISCOUNTS = <any> 'REGISTER_APPLY_RESTRICTED_DISCOUNTS',
    CHANGE_SETTINGS = <any> 'REGISTER_CHANGE_SETTINGS',
    EDIT_ITEM = <any> 'REGISTER_EDIT_ITEM',
    ISSUE_REFUNDS = <any> 'REGISTER_ISSUE_REFUNDS',
    OPEN_CASH_DRAWER_OUTSIDE_SALE = <any> 'REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE',
    VIEW_SUMMARY_REPORTS = <any> 'REGISTER_VIEW_SUMMARY_REPORTS'
}
