/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1FeeType {
    CAGST = <any> 'CA_GST',
    CAHST = <any> 'CA_HST',
    CAPST = <any> 'CA_PST',
    CAQST = <any> 'CA_QST',
    JPCONSUMPTIONTAX = <any> 'JP_CONSUMPTION_TAX',
    CAPEIPST = <any> 'CA_PEI_PST',
    USSALESTAX = <any> 'US_SALES_TAX',
    OTHER = <any> 'OTHER'
}
