/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* V1InventoryEntry
*/
export class V1InventoryEntry {
    /**
    * The variation that the entry corresponds to.
    */
    'variationId'?: string;
    /**
    * The current available quantity of the item variation.
    */
    'quantityOnHand'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "variationId",
            "baseName": "variation_id",
            "type": "string"
        },
        {
            "name": "quantityOnHand",
            "baseName": "quantity_on_hand",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V1InventoryEntry.attributeTypeMap;
    }
}

