/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Category } from './v1Category';
import { V1Fee } from './v1Fee';
import { V1ItemImage } from './v1ItemImage';
import { V1ModifierList } from './v1ModifierList';
import { V1Variation } from './v1Variation';

/**
* V1Item
*/
export class V1Item {
    /**
    * The item\'s ID. Must be unique among all entity IDs ever provided on behalf of the merchant. You can never reuse an ID. This value can include alphanumeric characters, dashes (-), and underscores (_).
    */
    'id'?: string;
    /**
    * The item\'s name.
    */
    'name'?: string;
    /**
    * The item\'s description.
    */
    'description'?: string;
    /**
    * The item\'s type. This value is NORMAL for almost all items. See [V1ItemType](#type-v1itemtype) for possible values
    */
    'type'?: string;
    /**
    * The color of the discount\'s display label in Square Register, if not the default color. The default color is 9da2a6. See [V1ItemColor](#type-v1itemcolor) for possible values
    */
    'color'?: string;
    /**
    * The text of the item\'s display label in Square Register. Only up to the first five characters of the string are used.
    */
    'abbreviation'?: string;
    /**
    * Indicates whether the item is viewable from the merchant\'s online store (PUBLIC) or PRIVATE. See [V1ItemVisibility](#type-v1itemvisibility) for possible values
    */
    'visibility'?: string;
    /**
    * If true, the item can be added to shipping orders from the merchant\'s online store.
    */
    'availableOnline'?: boolean;
    'masterImage'?: V1ItemImage;
    'category'?: V1Category;
    /**
    * The item\'s variations. You must specify at least one variation.
    */
    'variations'?: Array<V1Variation>;
    /**
    * The modifier lists that apply to the item, if any.
    */
    'modifierLists'?: Array<V1ModifierList>;
    /**
    * The fees that apply to the item, if any.
    */
    'fees'?: Array<V1Fee>;
    /**
    * Deprecated. This field is not used.
    */
    'taxable'?: boolean;
    /**
    * The ID of the item\'s category, if any.
    */
    'categoryId'?: string;
    /**
    * If true, the item can be added to pickup orders from the merchant\'s online store. Default value: false
    */
    'availableForPickup'?: boolean;
    /**
    * The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
    */
    'v2Id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "string"
        },
        {
            "name": "availableOnline",
            "baseName": "available_online",
            "type": "boolean"
        },
        {
            "name": "masterImage",
            "baseName": "master_image",
            "type": "V1ItemImage"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "V1Category"
        },
        {
            "name": "variations",
            "baseName": "variations",
            "type": "Array<V1Variation>"
        },
        {
            "name": "modifierLists",
            "baseName": "modifier_lists",
            "type": "Array<V1ModifierList>"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "Array<V1Fee>"
        },
        {
            "name": "taxable",
            "baseName": "taxable",
            "type": "boolean"
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string"
        },
        {
            "name": "availableForPickup",
            "baseName": "available_for_pickup",
            "type": "boolean"
        },
        {
            "name": "v2Id",
            "baseName": "v2_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1Item.attributeTypeMap;
    }
}

