/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ModifierList } from './v1ModifierList';

/**
* 
*/
export class V1ListModifierListsResponse {
    /**
    * 
    */
    'items'?: Array<V1ModifierList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<V1ModifierList>"
        }    ];

    static getAttributeTypeMap() {
        return V1ListModifierListsResponse.attributeTypeMap;
    }
}

