/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class V1ListTimecardsRequest {
    /**
    * The order in which timecards are listed in the response, based on their created_at field. See [SortOrder](#type-sortorder) for possible values
    */
    'order'?: string;
    /**
    * If provided, the endpoint returns only timecards for the employee with the specified ID.
    */
    'employeeId'?: string;
    /**
    * If filtering results by their clockin_time field, the beginning of the requested reporting period, in ISO 8601 format.
    */
    'beginClockinTime'?: string;
    /**
    * If filtering results by their clockin_time field, the end of the requested reporting period, in ISO 8601 format.
    */
    'endClockinTime'?: string;
    /**
    * If filtering results by their clockout_time field, the beginning of the requested reporting period, in ISO 8601 format.
    */
    'beginClockoutTime'?: string;
    /**
    * If filtering results by their clockout_time field, the end of the requested reporting period, in ISO 8601 format.
    */
    'endClockoutTime'?: string;
    /**
    * If filtering results by their updated_at field, the beginning of the requested reporting period, in ISO 8601 format.
    */
    'beginUpdatedAt'?: string;
    /**
    * If filtering results by their updated_at field, the end of the requested reporting period, in ISO 8601 format.
    */
    'endUpdatedAt'?: string;
    /**
    * If true, only deleted timecards are returned. If false, only valid timecards are returned.If you don\'t provide this parameter, both valid and deleted timecards are returned.
    */
    'deleted'?: boolean;
    /**
    * The maximum integer number of employee entities to return in a single response. Default 100, maximum 200.
    */
    'limit'?: number;
    /**
    * A pagination cursor to retrieve the next set of results for your original query to the endpoint.
    */
    'batchToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "order",
            "baseName": "order",
            "type": "string"
        },
        {
            "name": "employeeId",
            "baseName": "employee_id",
            "type": "string"
        },
        {
            "name": "beginClockinTime",
            "baseName": "begin_clockin_time",
            "type": "string"
        },
        {
            "name": "endClockinTime",
            "baseName": "end_clockin_time",
            "type": "string"
        },
        {
            "name": "beginClockoutTime",
            "baseName": "begin_clockout_time",
            "type": "string"
        },
        {
            "name": "endClockoutTime",
            "baseName": "end_clockout_time",
            "type": "string"
        },
        {
            "name": "beginUpdatedAt",
            "baseName": "begin_updated_at",
            "type": "string"
        },
        {
            "name": "endUpdatedAt",
            "baseName": "end_updated_at",
            "type": "string"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "batchToken",
            "baseName": "batch_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1ListTimecardsRequest.attributeTypeMap;
    }
}

