/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export class V1ListEmployeesRequest {
    /**
    * The order in which employees are listed in the response, based on their created_at field.      Default value: ASC See [SortOrder](#type-sortorder) for possible values
    */
    'order'?: string;
    /**
    * If filtering results by their updated_at field, the beginning of the requested reporting period, in ISO 8601 format
    */
    'beginUpdatedAt'?: string;
    /**
    * If filtering results by there updated_at field, the end of the requested reporting period, in ISO 8601 format.
    */
    'endUpdatedAt'?: string;
    /**
    * If filtering results by their created_at field, the beginning of the requested reporting period, in ISO 8601 format.
    */
    'beginCreatedAt'?: string;
    /**
    * If filtering results by their created_at field, the end of the requested reporting period, in ISO 8601 format.
    */
    'endCreatedAt'?: string;
    /**
    * If provided, the endpoint returns only employee entities with the specified status (ACTIVE or INACTIVE). See [V1ListEmployeesRequestStatus](#type-v1listemployeesrequeststatus) for possible values
    */
    'status'?: string;
    /**
    * If provided, the endpoint returns only employee entities with the specified external_id.
    */
    'externalId'?: string;
    /**
    * The maximum integer number of employee entities to return in a single response. Default 100, maximum 200.
    */
    'limit'?: number;
    /**
    * A pagination cursor to retrieve the next set of results for your original query to the endpoint.
    */
    'batchToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "order",
            "baseName": "order",
            "type": "string"
        },
        {
            "name": "beginUpdatedAt",
            "baseName": "begin_updated_at",
            "type": "string"
        },
        {
            "name": "endUpdatedAt",
            "baseName": "end_updated_at",
            "type": "string"
        },
        {
            "name": "beginCreatedAt",
            "baseName": "begin_created_at",
            "type": "string"
        },
        {
            "name": "endCreatedAt",
            "baseName": "end_created_at",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "batchToken",
            "baseName": "batch_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1ListEmployeesRequest.attributeTypeMap;
    }
}

