/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ModifierOption } from './v1ModifierOption';

/**
* V1ModifierList
*/
export class V1ModifierList {
    /**
    * The modifier list\'s unique ID.
    */
    'id'?: string;
    /**
    * The modifier list\'s name.
    */
    'name'?: string;
    /**
    * Indicates whether MULTIPLE options or a SINGLE option from the modifier list can be applied to a single item. See [V1ModifierListSelectionType](#type-v1modifierlistselectiontype) for possible values
    */
    'selectionType'?: string;
    /**
    * The options included in the modifier list.
    */
    'modifierOptions'?: Array<V1ModifierOption>;
    /**
    * The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
    */
    'v2Id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "selectionType",
            "baseName": "selection_type",
            "type": "string"
        },
        {
            "name": "modifierOptions",
            "baseName": "modifier_options",
            "type": "Array<V1ModifierOption>"
        },
        {
            "name": "v2Id",
            "baseName": "v2_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1ModifierList.attributeTypeMap;
    }
}

