/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1PageCellPlaceholderType {
    ALLITEMS = <any> 'ALL_ITEMS',
    DISCOUNTSCATEGORY = <any> 'DISCOUNTS_CATEGORY',
    REWARDSFINDER = <any> 'REWARDS_FINDER'
}
