/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* V1PaymentItemDetail
*/
export class V1PaymentItemDetail {
    /**
    * The name of the item\'s merchant-defined category, if any.
    */
    'categoryName'?: string;
    /**
    *  The item\'s merchant-defined SKU, if any.
    */
    'sku'?: string;
    /**
    * The unique ID of the item purchased, if any.
    */
    'itemId'?: string;
    /**
    * The unique ID of the item variation purchased, if any.
    */
    'itemVariationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryName",
            "baseName": "category_name",
            "type": "string"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "itemVariationId",
            "baseName": "item_variation_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1PaymentItemDetail.attributeTypeMap;
    }
}

