/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Money } from './v1Money';

/**
* V1SettlementEntry
*/
export class V1SettlementEntry {
    /**
    * The settlement\'s unique identifier.
    */
    'paymentId'?: string;
    /**
    * The settlement\'s current status. See [V1SettlementEntryType](#type-v1settlemententrytype) for possible values
    */
    'type'?: string;
    'amountMoney'?: V1Money;
    'feeMoney'?: V1Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentId",
            "baseName": "payment_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "amountMoney",
            "baseName": "amount_money",
            "type": "V1Money"
        },
        {
            "name": "feeMoney",
            "baseName": "fee_money",
            "type": "V1Money"
        }    ];

    static getAttributeTypeMap() {
        return V1SettlementEntry.attributeTypeMap;
    }
}

