/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1SettlementEntryType {
    ADJUSTMENT = <any> 'ADJUSTMENT',
    BALANCECHARGE = <any> 'BALANCE_CHARGE',
    CHARGE = <any> 'CHARGE',
    FREEPROCESSING = <any> 'FREE_PROCESSING',
    HOLDADJUSTMENT = <any> 'HOLD_ADJUSTMENT',
    PAIDSERVICEFEE = <any> 'PAID_SERVICE_FEE',
    PAIDSERVICEFEEREFUND = <any> 'PAID_SERVICE_FEE_REFUND',
    REDEMPTIONCODE = <any> 'REDEMPTION_CODE',
    REFUND = <any> 'REFUND',
    RETURNEDPAYOUT = <any> 'RETURNED_PAYOUT',
    SQUARECAPITALADVANCE = <any> 'SQUARE_CAPITAL_ADVANCE',
    SQUARECAPITALPAYMENT = <any> 'SQUARE_CAPITAL_PAYMENT',
    SQUARECAPITALREVERSEDPAYMENT = <any> 'SQUARE_CAPITAL_REVERSED_PAYMENT',
    SUBSCRIPTIONFEE = <any> 'SUBSCRIPTION_FEE',
    SUBSCRIPTIONFEEREFUND = <any> 'SUBSCRIPTION_FEE_REFUND',
    OTHER = <any> 'OTHER',
    INCENTEDPAYMENT = <any> 'INCENTED_PAYMENT',
    RETURNEDACHENTRY = <any> 'RETURNED_ACH_ENTRY',
    RETURNEDSQUARE275 = <any> 'RETURNED_SQUARE_275',
    SQUARE275 = <any> 'SQUARE_275',
    SQUARECARD = <any> 'SQUARE_CARD'
}
