/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The brand of a credit card.
*/
export enum V1TenderCardBrand {
    OTHERBRAND = <any> 'OTHER_BRAND',
    VISA = <any> 'VISA',
    MASTERCARD = <any> 'MASTER_CARD',
    AMERICANEXPRESS = <any> 'AMERICAN_EXPRESS',
    DISCOVER = <any> 'DISCOVER',
    DISCOVERDINERS = <any> 'DISCOVER_DINERS',
    JCB = <any> 'JCB',
    CHINAUNIONPAY = <any> 'CHINA_UNIONPAY',
    SQUAREGIFTCARD = <any> 'SQUARE_GIFT_CARD'
}
