/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* 
*/
export enum V1TenderType {
    CREDITCARD = <any> 'CREDIT_CARD',
    CASH = <any> 'CASH',
    THIRDPARTYCARD = <any> 'THIRD_PARTY_CARD',
    NOSALE = <any> 'NO_SALE',
    SQUAREWALLET = <any> 'SQUARE_WALLET',
    SQUAREGIFTCARD = <any> 'SQUARE_GIFT_CARD',
    UNKNOWN = <any> 'UNKNOWN',
    OTHER = <any> 'OTHER'
}
