/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Actions that resulted in a change to a timecard. All timecard events created with the Connect API have an event type that begins with `API`.
*/
export enum V1TimecardEventEventType {
    API_CREATE = <any> 'API_CREATE',
    API_EDIT = <any> 'API_EDIT',
    API_DELETE = <any> 'API_DELETE',
    REGISTER_CLOCKIN = <any> 'REGISTER_CLOCKIN',
    REGISTER_CLOCKOUT = <any> 'REGISTER_CLOCKOUT',
    DASHBOARD_SUPERVISOR_CLOSE = <any> 'DASHBOARD_SUPERVISOR_CLOSE',
    DASHBOARD_EDIT = <any> 'DASHBOARD_EDIT',
    DASHBOARD_DELETE = <any> 'DASHBOARD_DELETE'
}
