/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* V1TimecardEvent
*/
export class V1TimecardEvent {
    /**
    * The event\'s unique ID.
    */
    'id'?: string;
    /**
    * The ID of the timecard to list events for. See [V1TimecardEventEventType](#type-v1timecardeventeventtype) for possible values
    */
    'eventType'?: string;
    /**
    * The time the employee clocked in, in ISO 8601 format.
    */
    'clockinTime'?: string;
    /**
    * The time the employee clocked out, in ISO 8601 format.
    */
    'clockoutTime'?: string;
    /**
    * The time when the event was created, in ISO 8601 format.
    */
    'createdAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "string"
        },
        {
            "name": "clockinTime",
            "baseName": "clockin_time",
            "type": "string"
        },
        {
            "name": "clockoutTime",
            "baseName": "clockout_time",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1TimecardEvent.attributeTypeMap;
    }
}

