/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Item } from './v1Item';

/**
* 
*/
export class V1UpdateItemRequest {
    'body': V1Item;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "body",
            "baseName": "body",
            "type": "V1Item"
        }    ];

    static getAttributeTypeMap() {
        return V1UpdateItemRequest.attributeTypeMap;
    }
}

