/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* V1UpdateOrderRequest
*/
export class V1UpdateOrderRequest {
    /**
    * The action to perform on the order (COMPLETE, CANCEL, or REFUND). See [V1UpdateOrderRequestAction](#type-v1updateorderrequestaction) for possible values
    */
    'action': string;
    /**
    * The tracking number of the shipment associated with the order. Only valid if action is COMPLETE.
    */
    'shippedTrackingNumber'?: string;
    /**
    * A merchant-specified note about the completion of the order. Only valid if action is COMPLETE.
    */
    'completedNote'?: string;
    /**
    * A merchant-specified note about the refunding of the order. Only valid if action is REFUND.
    */
    'refundedNote'?: string;
    /**
    * A merchant-specified note about the canceling of the order. Only valid if action is CANCEL.
    */
    'canceledNote'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "shippedTrackingNumber",
            "baseName": "shipped_tracking_number",
            "type": "string"
        },
        {
            "name": "completedNote",
            "baseName": "completed_note",
            "type": "string"
        },
        {
            "name": "refundedNote",
            "baseName": "refunded_note",
            "type": "string"
        },
        {
            "name": "canceledNote",
            "baseName": "canceled_note",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1UpdateOrderRequest.attributeTypeMap;
    }
}

