/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The days of the week.
*/
export enum Weekday {
    MON = <any> 'MON',
    TUE = <any> 'TUE',
    WED = <any> 'WED',
    THU = <any> 'THU',
    FRI = <any> 'FRI',
    SAT = <any> 'SAT',
    SUN = <any> 'SUN'
}
