/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Sets the Day of the week and hour of the day that a business starts a  work week. Used for the calculation of overtime pay.
*/
export class WorkweekConfig {
    /**
    * UUID for this object
    */
    'id'?: string;
    /**
    * The day of the week on which a business week cuts over for compensation purposes. See [Weekday](#type-weekday) for possible values
    */
    'startOfWeek': string;
    /**
    * The local time at which a business week cuts over. Represented as a string in `HH:MM` format (`HH:MM:SS` is also accepted, but seconds are truncated).
    */
    'startOfDayLocalTime': string;
    /**
    * Used for resolving concurrency issues; request will fail if version provided does not match server version at time of request. If not provided, Square executes a blind write; potentially overwriting data from another write.
    */
    'version'?: number;
    /**
    * A read-only timestamp in RFC 3339 format; presented in UTC
    */
    'createdAt'?: string;
    /**
    * A read-only timestamp in RFC 3339 format; presented in UTC
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "startOfWeek",
            "baseName": "start_of_week",
            "type": "string"
        },
        {
            "name": "startOfDayLocalTime",
            "baseName": "start_of_day_local_time",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WorkweekConfig.attributeTypeMap;
    }
}

